# Generated by Django 2.0.6 on 2018-06-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('opening_hour', models.TimeField()),
                ('closing_hour', models.TimeField()),
                ('delivery_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('minimal_order_amount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
